# @file 01-help-ubuntu.yml
---
name: Launch --help

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install sysstat
      run: |
        sudo apt-get install -qq -yy sysstat
    - name: Launch script with --help
      run: |
        ./check_cpu_stats.sh --help
